---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaddem-back-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: back-container
        image: medgh/kaddem_back:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: back-service
spec:
  selector:
    app: back-app
  ports:
  - protocol: TCP
    port: 80        # Port exposed on the Service
    targetPort: 8080 # Port on the Pod that the Service forwards traffic to
  type: LoadBalancer # Or NodePort depending on your environment
